### ISSUE TITLE
Default serif math font looks out of place with lmodern

### ISSUE THREAD

**Issue by mars0i** [LanaSina/better_poster_latex#1]
Hi,

Thanks very much for better_poster for LaTeX!

It's still using the default serif math font for math mode.  This doesn't look good when you have some math embedeed within text, given the lmodern sans text that better_poster.sty is using.  

One quick and dirty solution (or maybe it's just a good solution?) is to add
```
\usepackage{sfmath}
```
Another package that works is `cmbright`, but if you embed math within bold text, e.g. in the findings block, the math won't be bold, and if you add `\mathbf`, you lose the italic.  `sfmath` looks good both in bold text and regular text.  (I don't think it's changing the amth to/from bold; I think it's just got an intermediate thickness that looks good either way with `lmodern` text.)

There are some other options described here:
https://tex.stackexchange.com/questions/24035/typeset-mathematical-symbols-also-in-sans-serif-font

`cmbright` was the best solution I found that (a) worked and (b) didn't require me to install another package.  I have not done any sort of thorough investigation.  It worked, looks good, and that's good enough for me.

**Comment by LanaSina** [comment]
Hi, thanks for raising the issue and sharing your suggestion! I'll check `\usepackage{sfmath}` .

**Comment by LanaSina** [comment]
> \usepackage{sfmath}
I chose this option. Thanks!
